import torch

SEQUENCE_START = 0
RANGE_NOTE_ON = 128
RANGE_NOTE_OFF = 128
RANGE_VEL = 32
RANGE_TIME_SHIFT = 100

START_IDX = {
    'note_on': 0,
    'note_off': RANGE_NOTE_ON,
    'time_shift': RANGE_NOTE_ON + RANGE_NOTE_OFF,
    'velocity': RANGE_NOTE_ON + RANGE_NOTE_OFF + RANGE_TIME_SHIFT
}

ADAM_BETA_1 = 0.9
ADAM_BETA_2 = 0.98
ADAM_EPSILON = 10e-9

LR_DEFAULT_START = 1.0
SCHEDULER_WARMUP_STEPS = 4000

TOKEN_END = RANGE_NOTE_ON + RANGE_NOTE_OFF + RANGE_VEL + RANGE_TIME_SHIFT
TOKEN_PAD = TOKEN_END + 1

VOCAB_SIZE = TOKEN_PAD + 1

TORCH_FLOAT = torch.float32
TORCH_INT = torch.int32

TORCH_LABEL_TYPE = torch.long

PREPEND_ZEROS_WIDTH = 4

CPU_DEVICE = torch.device("cpu")

USE_CUDA = 1

if USE_CUDA:
    TORCH_CUDA_DEVICE = torch.device("cuda:3")
else:
    TORCH_CUDA_DEVICE = None
